// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuG2wyzSl3VYONHXSu5ZGYcpoBQlRC_7s',
    appId: '1:965866791903:web:15f2e50457f65147a61a6a',
    messagingSenderId: '965866791903',
    projectId: 'eldalala-2d156',
    authDomain: 'eldalala-2d156.firebaseapp.com',
    storageBucket: 'eldalala-2d156.appspot.com',
    measurementId: 'G-T3CQE08SW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEDQY5pevomHZQAagS0wU_8ycdRWNsLXc',
    appId: '1:965866791903:android:9d5e530e17abf8f1a61a6a',
    messagingSenderId: '965866791903',
    projectId: 'eldalala-2d156',
    storageBucket: 'eldalala-2d156.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjbUFZ0EwXieFxlznVNr5Iw03By_xAocs',
    appId: '1:965866791903:ios:f81c958f526e12a1a61a6a',
    messagingSenderId: '965866791903',
    projectId: 'eldalala-2d156',
    storageBucket: 'eldalala-2d156.appspot.com',
    androidClientId: '965866791903-aberiap2nneqn5k1arask0gn7u627vfu.apps.googleusercontent.com',
    iosClientId: '965866791903-43jsjeuj3nu3964j04o0hab6mcf6509m.apps.googleusercontent.com',
    iosBundleId: 'com.example.eldalala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjbUFZ0EwXieFxlznVNr5Iw03By_xAocs',
    appId: '1:965866791903:ios:52410d00eac1372aa61a6a',
    messagingSenderId: '965866791903',
    projectId: 'eldalala-2d156',
    storageBucket: 'eldalala-2d156.appspot.com',
    androidClientId: '965866791903-aberiap2nneqn5k1arask0gn7u627vfu.apps.googleusercontent.com',
    iosClientId: '965866791903-erjjcoqtucgoskr78r8ic5hn6rocutlv.apps.googleusercontent.com',
    iosBundleId: 'com.example.eldalala.RunnerTests',
  );
}
